### PR TITLE
Add Puppet PC1 repository to pbuilder

### PR DESCRIPTION
**Pull request by domcleal**
1. https://github.com/theforeman/foreman-packaging/issues/1491
1. this
1. https://github.com/theforeman/foreman-packaging/issues/1492

### CODE REVIEW

**Comment by mmoll** [comment]
The PC1 and non-PC1 repos are enabled after this, I guess the selection of 3 vs. 4 will be puppet vs. puppet-agent?

**Comment by domcleal** [comment]
Yes, that's right. Both will be needed as older branches will build against `puppet`.

**Comment by mmoll** [comment]
allright, as puppet-agent doesn't seem to provide puppet, this should work...

**Comment by mmoll** [comment]
merged, thanks @domcleal!

**Pull request merged**
