### PR TITLE
add yum.tfm.o to Fastly config

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by evgeni** [comment]
When this is approved, merged and executed, I will switch the DNS with Ohad.
The corresponding log buckets exist in Rackspace already (there is no good Ansible module for that).

**Comment by ehelms** [comment]
@evgeni Make it so!

**Comment by mmoll** [comment]
merged, спасибо Женя!

**Comment by evgeni** [comment]
executed, works. mailed ohad to update the dns

**Pull request merged**
