### PR TITLE
update selinux to 1.6.1

### PR DESCRIPTION
**Pull request by evgeni**
Fixes GH-466

### CODE REVIEW

**Comment by evgeni** [comment]
@mmoll I had a look, and it seems we don't use any APIs that were broken in 1.x

**Comment by mmoll** [comment]
@evgeni this is pretty great, let's roll this out... :bomb:

**Comment by mmoll** [comment]
@evgeni aaand it's broken :boom::
```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Selinux::Fcontext[fcontext-www]:
  has no parameter named 'context'
  has no parameter named 'pathname' (file: /etc/puppetlabs/code/environments/production/modules/web/manifests/init.pp, line: 51) on node web02.rackspace.theforeman.org
```

**Comment by evgeni** [comment]
Fuck. I of course only looked at their examples, and these use the old syntax. :pouting_cat:

**Comment by evgeni** [comment]
Can you try changing pathname to pathspec and context to seltype?

**Comment by mmoll** [comment]
Better :+1:
Next one now:
```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Selinux::Module[rsync_debug]: has no parameter named 'source' (file: /etc/puppetlabs/code/environments/production/modules/foreman_debug_rsync/manifests/config.pp, line: 25) on node web02.rackspace.theforeman.org
```

**Comment by evgeni** [comment]
source -> source_te

**Comment by mmoll** [comment]
Changed modules/freight/manifests/user.pp also, now it applies :tada:

**Comment by evgeni** [comment]
Nice.
Can you open a PR so it's in git?

**Comment by mmoll** [comment]
:ok:

**Comment by evgeni** [comment]
Thanks. And sorry for the noise. And the fact that I am on my mobile w/o a sane way to submit patches.

**Comment by mmoll** [comment]
GH-857

**Pull request merged**
