### PR TITLE
flip web to website01

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by evgeni** [comment]
needs to happen together with https://github.com/theforeman/jenkins-jobs/pull/510

**Comment by ekohl** [comment]
> needs to happen together with [theforeman/jenkins-jobs#510](https://github.com/theforeman/jenkins-jobs/pull/510)

We can modify the deploy job to deploy to both places for some time.

**Comment by evgeni** [comment]
> > needs to happen together with [theforeman/jenkins-jobs#510](https://github.com/theforeman/jenkins-jobs/pull/510)
> 
> We can modify the deploy job to deploy to both places for some time.

Sure. But do we have to? :)

**Comment by ekohl** [comment]
I don't know how long the migration will be. We don't have that many changes to the website and we're also changing the hostname so there's no DNS TTLs so it's probably OK not to.

**Pull request merged**
