### PR TITLE
Add pcreech ssh-key

### PR DESCRIPTION
**Pull request by pcreech**

### CODE REVIEW

**Comment by zjhuntin** [comment]
ACK

**Comment by ehelms** [comment]
@pcreech Can you send a discourse thread with this request?

**Comment by pcreech** [comment]
https://community.theforeman.org/t/request-to-add-pcreech-to-foreman-infra-ssh-keys/10523

**Comment by evgeni** [comment]
the thread got 6 likes in a week, so we should be good?

**Comment by zjhuntin** [comment]
I think we are good to go here.

**Comment by ekohl** [comment]
Thanks, will add the user in Foreman and discuss the password offline.

**Pull request merged**
