### PR TITLE
Fixes #15595 - Do not test with Jenkins on 1.9.3

### PR DESCRIPTION
**Pull request by akofink**
Dependent on https://github.com/theforeman/foreman-packaging/pull/1212

### CODE REVIEW

**Comment by domcleal** [comment]
Fine by me, up to you @mbacovsky or @tstrachota.

**Comment by mmoll** [comment]
maybe also add 2.3?

**Comment by akofink** [comment]
@mmoll I like that idea, but should it be associated with this issue or a separate one?

**Comment by mmoll** [comment]
I'd say just do it. We do run hammer on Ubuntu/xenial under 2.3, so we did miss that a few months ago...

**Comment by akofink** [comment]
@domcleal Is this blocked by anything else?

**Comment by mmoll** [comment]
Personally I'd maybe open a PR against at least hammer-cli to update the gemspec accordingly. And otherwise the two people mentioned are the hammer wizards... But if the failing tests are real pain for you, I'm also not against merging this.

**Comment by domcleal** [comment]
@akofink it's waiting for one of the two maintainers to confirm they want to drop support.

**Comment by mbacovsky** [comment]
@domcleal, I'm fine with dropping 1.9.3 testing.

**Comment by domcleal** [comment]
Merged, thanks.

**Pull request merged**
