### PR TITLE
Remove skottler key as per dev-list thread

### PR DESCRIPTION
**Pull request by GregSutcliffe**
Just cleanup I think - I don't see Sam's user in the Foreman YAML ENC...

### CODE REVIEW

**Comment by ekohl** [comment]
Shouldn't there be a ```user { 'samkottler': ensure => absent }``` as well?

**Comment by mmoll** [comment]
it's in `puppet/modules/users/manifests/init.pp` and should be changed there, too

**Comment by mmoll** [comment]
hrm, or rather added with absent... It's strange that he's not in the YAML, as $users is probably not undef.

**Comment by ohadlevy** [comment]
I suspect that in order to actually remove it, you need to change the
internal foreman ENC output. (change the parameter value).

**Comment by mmoll** [comment]
@GregSutcliffe were there insights on how to remove the user?

**Comment by ekohl** [comment]
@mmoll shouldn't we just maintain the user in the ENC but with ```ensure => absent```?

**Comment by mmoll** [comment]
`users:account` always set `ensure     => present`

**Comment by ekohl** [comment]
https://github.com/theforeman/foreman-infra/pull/332 should solve that but I haven't tested it.

**Comment by mmoll** [comment]
mergedm thanks @GregSutcliffe!

**Pull request merged**
