### PR TITLE
use upstream jjb and drop the use of schedule-failed-builds

### PR DESCRIPTION
**Pull request by evgeni**
Closes: #491

### CODE REVIEW

**Comment by mmoll** [comment]
I have no idea what I'm doing, but this looks legit :+1:

**Comment by mmoll** [comment]
merged, спасибо Женя!

**Comment by evgeni** [comment]
Now I wonder if that should've been `ensure: latest` to actually update from PyPI.

**Comment by mmoll** [comment]
hrm... on a related note: `Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Class[Jenkins_job_builder]: has no parameter named 'git_revision' on node master01.rackspace.theforeman.org`

**Comment by ekohl** [comment]
> Now I wonder if that should've been ensure: latest to actually update from PyPI.

I considered that too but not sure that's wise. Maybe wiser to make it a param and pin it to an explicit version?

**Comment by evgeni** [comment]
Oups. Can you remove the two git_ params from Foreman?

**Comment by mmoll** [comment]
I think this needs to get removed in `puppet/modules/jenkins_job_builder/manifests/*`

**Comment by mmoll** [comment]
Aw, sorry... found it in an unexpected place. Fixed.

**Comment by evgeni** [comment]
That's where I removed it ;)

**Pull request merged**
