### PR TITLE
Add AWStats module for web02

### PR DESCRIPTION
**Pull request by GregSutcliffe**
This has already been applied to Web02 using "puppet apply" while developing it, so it should be fine. Resulting output is viewable at http://downloads.theforeman.org/awstats

### CODE REVIEW

**Comment by GregSutcliffe** [comment]
That's a fair point. I can move it to the debugs vhost which is password protected, would that do?

**Comment by ekohl** [comment]
Sounds like a good idea

**Comment by GregSutcliffe** [comment]
@ekohl updated and applied on web02

**Comment by ohadlevy** [comment]
Is it just me or the links are broken?

**Comment by GregSutcliffe** [comment]
@ohadlevy example? the menu the top works for me, drilldown subpages like awstats.deb.alldomains.html are not currently being generated.

**Comment by ohadlevy** [comment]
I mean the vhost file (Deb, yum etc) in the link you sent earlier

**Comment by GregSutcliffe** [comment]
As per @ekohl's suggestion to protect them, they're now at http://debugs.theforeman.org/awstats

**Comment by GregSutcliffe** [comment]
Oh, i do see a typo in the puppet code that was leftover, thanks @ohadlevy - updated.

**Comment by mmoll** [comment]
merged, thanks @GregSutcliffe!

**Pull request merged**
