### PR TITLE
[RFC] Document Jenkins Job Naming conventions

### PR DESCRIPTION
**Pull request by ekohl**
This is very much a work in progress and I know I forgot many conventions. Please suggest those I forgot :)

### CODE REVIEW

**Comment by ehelms** [comment]
Just checking if this should go in here in stead -- https://github.com/theforeman/foreman-infra/tree/master/puppet/modules/jenkins_job_builder

**Comment by ehelms** [comment]
PR tests follow:

```
{git-repo}-{optional concern}-pr-test
```

Where {optional-concern} is for things like packaging repo that may have a job for rpms and another for deb

**Comment by ehelms** [comment]
You could mention also that general rule of thumb is specific -> general (going left to right) with naming conventions. Where the left hand side generally denotes a project of some type and the right hand a categorization.

**Comment by komidore64** [comment]
`{git-repo}-{optional-concern}-pr-test` is ideal for pull requests?

I've written a handful of jobs that are `{git-repo}-pull-request` so I guess those will need to be changed :)

**Comment by ehelms** [comment]
Well, do we want to standardize on pr-test ? Since its shorter? I think we should add what we know here and merge it. Then we can iterate without leaving this open.

**Comment by ekohl** [comment]
I'd prefer `pr-test`.

**Comment by komidore64** [comment]
i'd prefer `*-pr` only because we may want to run other things than just tests on a pull-request, but that's a nitpick.

I won't be upset if i'm overruled for `*-pr-test`.

**Comment by ehelms** [comment]
That's fair, `-test` is perhaps a bit extraneous unless we started doing things like:

```
blah-pr-test
blah-pr-rubocop
```

Maybe?

**Comment by ehelms** [comment]
I say lets add the pr one and merge this.

**Comment by komidore64** [comment]
:+1:

**Comment by ekohl** [comment]
> You could mention also that general rule of thumb is specific -> general (going left to right) with naming conventions. Where the left hand side generally denotes a project of some type and the right hand a categorization.

Following this logic it would be `{repo}-{concern}-{type}-{pr}` - i.e. `foreman-test-pr` and `foreman-rubocop-pr`, right?

**Comment by ekohl** [comment]
Added PR testing and moved it to the main README since that's not really big anyway and guarantees visibility.

**Pull request merged**
