### PR TITLE
Use Rubygems 3.0.3 with Ruby 2.6

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by mmoll** [comment]
Ruby 2.6 is bringing Rubygems 3.0.x, which is not compatible with some older versions and downgrading to an older version requires `--force`.

**Comment by ekohl** [comment]
Do we really want to divert from the standard Ruby 2.6? We could easily mask issues that we'd hit in practice.

**Comment by mmoll** [comment]
True, but then I'd suggest to just remove the version check and take what's coming which each Ruby at install time...

**Comment by mmoll** [comment]
As it turns out, `slave::rvm_config` is already capable of doing all that... how about this? :)

**Pull request merged**
