### PR TITLE
Adjusting to properly use RVM

### PR DESCRIPTION
**Pull request by evgeni**
See also https://github.com/SatelliteQE/robottelo-ci/pull/545

### CODE REVIEW

**Comment by evgeni** [comment]
IMHO slightly cleaner as #282 ;)

**Comment by zjhuntin** [comment]
@evgeni Agreed, I took my PR down.

**Comment by mmoll** [comment]
I'm a bit concerned about this PR as the errors this PR is supposed to fix can't be seen on ci.theforeman.org, if I understood correctly...

**Comment by evgeni** [comment]
Correct, this is to fix an issue we have on our downstream (Satellite) Jenkins, which does not have `rvm.sh` in `/etc/profile.d/`, albeit RVM is working fine otherwise.

**Comment by mmoll** [comment]
I think this needs to get changed on the downstream CI side, sorry...

**Comment by evgeni** [comment]
Fair enough, we have implemented a workaround in https://github.com/SatelliteQE/robottelo-ci/issues/635, so we'll keep it.

**Pull request closed without merging**
