### PR TITLE
fix awk call in deploy-yumrepo

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by evgeni** [comment]
and of course I didn't test `purgecdn` part

**Comment by evgeni** [comment]
you can't use single quotes inside an `awk` expression because why would you

**Review by ekohl — APPROVED** [review]
So this never worked?

**Comment by evgeni** [comment]
the old capistrano code worked, because it had double quotes, your translation didn't as you used single quotes.

**Comment by evgeni** [comment]
I just did comment that part in the web01 deployment, as I didn't want to purge twice

**Pull request merged**
