### PR TITLE
Run repoclosure on packaging PRs

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by ekohl** [comment]
Looks good but probably needs https://github.com/theforeman/obal/pull/103

**Comment by ehelms** [comment]
I'll merge once https://github.com/theforeman/foreman-packaging/pull/2607 is merged

**Comment by ekohl** [comment]
We'll also need a similar change cherry picked to `rpm/1.18` before merging this.

**Comment by ehelms** [comment]
@ekohl @komidore64 Jus tneeds this CP now --https://github.com/theforeman/foreman-packaging/pull/2663

**Pull request merged**
