### PR TITLE
Test foreman_remote_execution against 1.10-stable

### PR DESCRIPTION
**Pull request by stbenjam**

### CODE REVIEW

**Comment by stbenjam** [comment]
Hold off on merging this just yet

**Comment by stbenjam** [comment]
Ready to go

**Comment by domcleal** [comment]
Thanks @stbenjam.

**Comment by domcleal** [comment]
@stbenjam please note that it's now failing: http://ci.theforeman.org/job/test_plugin_foreman_remote_execution_master/69/

**Pull request merged**
