### PR TITLE
Added Discovery 16.2 branch

### PR DESCRIPTION
**Pull request by lzap**
Only merge once we branch off 2.2 release.

### CODE REVIEW

**Comment by ehelms** [comment]
Just ping this PR when that is ready to go

**Comment by ekohl** [comment]
> Only merge once we branch off 2.2 release.

2.2 is GA. Did you mean 2.3 (which was also branched by now)?

**Comment by lzap** [comment]
Yes, updated. I meant 2.3 but since I forgot to do this step last time I just blindly increased the numbers using my editor feature.

**Comment by ehelms** [comment]
We have moved the Jenkins job definitions over to https://github.com/theforeman/jenkins-jobs -- please re-open your PR against this new repository.

**Comment by lzap** [comment]
https://github.com/theforeman/jenkins-jobs/pull/42

**Pull request closed without merging**
