### PR TITLE
Build core DEB PRs only on x86

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by ekohl** [comment]
Any reason to not do this for foreman-proxy? Should we just drop ARM altogether since it's being phased out by Scaleway?

**Comment by mmoll** [comment]
All the other builds, except some dependencies are not built on ARM anyway.

I'd like to keep it as long as possible for 1.24 and 2.0.

**Comment by ekohl** [comment]
Should we look at the branch then and only skip it in develop?

**Comment by mmoll** [comment]
> Should we look at the branch then and only skip it in develop?

Like that? :)

**Pull request merged**
