### PR TITLE
Move foreman plugins release to multi-stage parallel

### PR DESCRIPTION
**Pull request by ehelms**
Provides better visual for internal stages inside parallel steps:

screenshot from 2018-08-29 11-54-34

### CODE REVIEW

**Comment by komidore64** [comment]
well ... maybe see if we can abbreviate those names, so there isn't gross wordwrap?

**Comment by komidore64** [comment]
`repo-cl-1.18-el7` or something?

**Comment by ekohl** [comment]
Perhaps just `Repoclosure 1.18-el7`? Then it uses 2 lines but not such an ugly one.

**Comment by ehelms** [comment]
I tried that and it did not help. The UI appears to treat characters all equally and simply wrap after a certain number of them.

**Comment by komidore64** [comment]
@ehelms understood. thanks for checking! :+1:

**Pull request merged**
