### PR TITLE
Run Redmine on HTTPS only with a redirect

### PR DESCRIPTION
**Pull request by ekohl**
This is untested. Probably best to roll it out with noop to see the diff before applying it.

### CODE REVIEW

**Comment by ekohl** [comment]
@GregSutcliffe @mmoll I'd like to roll this out soonish (not today due to other priorities). Could you have a look?

**Comment by GregSutcliffe** [comment]
LGTM. I was planning to roll out the snapshot script later on today as well, I can add this to my list.

**Comment by GregSutcliffe** [comment]
Deploying now, hang tight :)

**Comment by GregSutcliffe** [comment]
All good apart from #696 which is also merged. Ty @ekohl

**Pull request merged**
