### PR TITLE
Use koji instead of kkoji

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by komidore64** [comment]
Why is this change needed?

**Comment by ehelms** [comment]
The `kkoji` symlink we added doesn't actually work, and we adjusted the config for koji to be `.koji/config` which means standard `koji` will use the proper configuration value. This fixes the jobs that still use this bash script such as katello RPM nightly build.

**Comment by komidore64** [comment]
awesome!

ACK

**Comment by ekohl** [comment]
@komidore64 The way I understand it is that koji looks for a section as the binary is called. If it's called as ```kkoji```, it looks for ```[kkoji]``` in ```~/.koji/config```. If it's called as ```koji```, then ```[koji]```. Our config has ```[koji]```, so we should call it as koji.

**Comment by komidore64** [comment]
thank yall for the clarification

**Comment by ehelms** [comment]
@komidore64 Thanks for the question!

**Comment by ehelms** [comment]
@ekohl I *think* so, once this is merged I'll monitor and remove it if so.

**Pull request merged**
