### PR TITLE
Remove foreman_remote_execution CI jobs

### PR DESCRIPTION
**Pull request by adamruzicka**

### CODE REVIEW

**Comment by mmoll** [comment]
Should the PR tests also get removed?

**Comment by mmoll** [comment]
Merged, díky @adamruzicka.

Somebody:tm: should remove the webhooks in the Github repo.

**Comment by adamruzicka** [comment]
Disabled the webhook

**Comment by tbrisker** [comment]
@adamruzicka why did you remove the build test job? iiuc, the GH action only replaces the PR tests. And considering that the PR action runs on ubuntu, i'm worried this might lead to failures on centos we'll only find when building the packages if build test aren't run after merge.

**Pull request merged**
