### PR TITLE
disable arm builds for 2.1 and nightly

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by evgeni** [comment]
@mmoll I have no idea what I am doing here, so please help :)

**Comment by mmoll** [comment]
In these two jobs filtering needs to be done for `arch` and basically the existing filter needs to get extended by one that comes back true for `(arch = "armv8" && (version == "2.0" || version == "1.24")`. To make things easier, 1.22 and 1.23 can get IMHO removed anyway.

**Comment by mmoll** [comment]
> To make things easier, 1.22 and 1.23 can get IMHO removed anyway.

See GH-1378

**Comment by mmoll** [comment]
needs a rebase now :)

**Comment by evgeni** [comment]
@mmoll done, also simplified the focal exclude, now that we don't build armv8 at all in nightly

**Pull request merged**
