### PR TITLE
Remove deploy_katello_site job

### PR DESCRIPTION
**Pull request by ekohl**
This openshift site no longer appears to be operational so we can remove the whole job.

### CODE REVIEW

**Comment by mmoll** [comment]
This can go, yes... However, it seems www.katello.org also has no DNS entry, shouldn't there be a redirect to https://theforeman.org/plugins/katello/ ? katello.org rediects to www.katello.org.

**Comment by ekohl** [comment]
It should - not sure who the person to talk to is.

**Comment by ekohl** [comment]
https://community.theforeman.org/t/katello-org-domain/8119

**Comment by mmoll** [comment]
merged, bedankt @ekohl!

**Pull request merged**
