### PR TITLE
Replace customised apache module with pl-apache

### PR DESCRIPTION
**Pull request by domcleal**
Allows web server to be replaced with an EL7 host, simplifies and
standardises configuration of vhosts.

---

Please let me know before merging this, or let me do it so we don't cause an outage if there's an issue.  My no-op test results look reasonable.

### CODE REVIEW

**Comment by ehelms** [comment]
:+1:

**Comment by domcleal** [comment]
I'll apply this tomorrow, sent a notice to the main lists: https://groups.google.com/forum/#!topic/foreman-users/Kh5iNU4P07w.

**Comment by mmoll** [comment]
:+1:

**Comment by domcleal** [comment]
Thanks for the reviews.

I'm going to let this apply to the main web01 server, then I plan to spin up a new EL7 server (web02) and migrate to it in the next week or so.

**Comment by domcleal** [comment]
Some errata:

* 95a2d21: the apache::vhost `port` parameter must be specified for name based virtual hosts
* 5bb0bab: web::jenkins had to be converted too, I forgot it ran Apache (as a proxy to the main service)
* 55c4469: refresh theforeman modules for the main Foreman/Puppet master to be compatible

**Pull request merged**
