### PR TITLE
Fixes #33444 - drop old (2016) debian signing key

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by evgeni** [comment]
I'd merge this the day after 3.2 goes GA.

**Review by ekohl — APPROVED** [review]
Why the day after 3.2 goes GA?

**Comment by evgeni** [comment]
mostly because infra changes aren't merged *together* with the release, and I think the promise was "3.0 will continue being verifyable with the old key as long as it's a supported release", which it won't be the day after 3.2 is out

**Comment by ekohl** [comment]
That makes sense, thanks!

**Comment by evgeni** [comment]
The key (563278F6) expired yesterday, and thus can't be used for signing anymore.

Instead of prolonging it again, I am going to merge this PR one day *before* 3.2 goes GA.

**Review by ekohl — APPROVED** [review]
I'm ok with that. It should unblock our nightly packages. It will probably also fix publishing 3.2 once we release it.

**Pull request merged**
