### PR TITLE
Redmine improvements

### PR DESCRIPTION
**Pull request by ekohl**
* PostgreSQL tuning
* Handle VCS repo in puppet. This should match the existing situation

### CODE REVIEW

**Comment by evgeni** [comment]
LGTM, but I'd prefer if @GregSutcliffe as master-of-redmine would ack

**Comment by GregSutcliffe** [comment]
Yeah, looks ok to me too. I'll deploy this (probably Thursday now) and manually run puppet to ensure it's ok.

**Comment by GregSutcliffe** [comment]
Merged, deploying now

**Comment by GregSutcliffe** [comment]
Seems we all missed an error :package: 
```
Error: Failed to apply catalog: Could not find dependency File[/usr/share/redmine] for Vcsrepo[/usr/share/redmine] at /etc/puppetlabs/code/environments/production/modules/redmine/manifests/init.pp:102
```

**Pull request merged**
