### PR TITLE
use utf8mb4 for MySQL in tests

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by mmoll** [comment]
I'm unsure what consequences this has for non-develop tests

**Comment by ares** [comment]
You mean plugins e.g.? I'd merge and see what happens, we only had to fix two too long indices in core. We can always revert if it is too bad.

**Comment by mmoll** [comment]
> You mean plugins

Nope, but I'd expect all versions that don't have the `:limit => 40` migrations to fail in `db:migrate`

**Comment by ares** [comment]
oh, so we'd better to get the one fixing it in before? do you want me to send separate PR just with the limit?

**Comment by mmoll** [comment]
> do you want me to send separate PR just with the limit

If there are no better options, yes. And once that got cherry-picked down to 1.15, this PR can get in.

**Comment by ekohl** [comment]
Is this something we should set in the mysql connection so users don't forget to set it?

**Comment by ares** [comment]
we could do it, not sure what the outcome for existing users would be though

**Pull request merged**
