### PR TITLE
Disable sudo for the jenkins user on non-Debian

### PR DESCRIPTION
**Pull request by ekohl**

### CODE REVIEW

**Comment by ekohl** [comment]
Looking a bit closer I suspect most of this is because of pbuilder and chown

**Comment by ekohl** [comment]
Updated to maintain sudo on Debian, but disable it elsewhere. Should be a first step.

**Comment by mmoll** [comment]
let's try it...

**Comment by mmoll** [comment]
merged, bedankt @ekohl!

**Pull request merged**
