### PR TITLE
Include Debian packaging when relevant

### PR DESCRIPTION
**Pull request by ekohl**
Currently we've created a hostgroup for Debian just to include this class.  This creates a parity between deb and rpm packaging

Also marks private classes as such

### CODE REVIEW

**Comment by mmoll** [comment]
tests fail :broken_heart:

**Comment by ekohl** [comment]
Yes, the SSH setup is not very friendly to unit testing. In another class we've disabled it. I'll have a look at that here as well.

**Comment by ekohl** [comment]
:green_heart: now. When deployed, the classes within Foreman also need to be modified.

**Comment by mmoll** [comment]
merged, bedankt @ekohl!

**Pull request merged**
