### PR TITLE
Add docker module and configure slave to install and run docker

### PR DESCRIPTION
**Pull request by ehelms**
This is untested and a bit of a leap of faith that the module will just work and configure the slaves that can support docker properly for us. According to (https://github.com/puppetlabs/puppetlabs-docker#description) this should configure on most of our slaves and I assume ignore the ARM slaves. This is my first time trying to add additional puppet modules to our infrastructure so please be gentle and let me know what thoughts are towards any additional config this might need.

### CODE REVIEW

**Comment by mmoll** [comment]
@GregSutcliffe that module could also be of use for the discourse install, I presume?

**Comment by ehelms** [comment]
@ekohl Any further thoughts here? I assume this will just work but I anticipate having to deal with a few issues.

**Comment by mmoll** [comment]
yeah, let's pull the trigger on that :gun:

**Comment by mmoll** [comment]
merged, thanks @ehelms!

**Pull request merged**
