### PR TITLE
Add updated HEADER, and missing stagingyum entries

### PR DESCRIPTION
**Pull request by ehelms**
Is this enough to get a DNS entry for `stagingyum.theforeman.org` or do I need @ekohl / @evgeni to add one?

### CODE REVIEW

**Comment by ehelms** [comment]
Is it expected that `http://web01.osuosl.theforeman.org/` serves the same page as `deb.theforeman.org` ?

**Comment by ekohl** [comment]
> Is this enough to get a DNS entry for `stagingyum.theforeman.org` or do I need @ekohl / @evgeni to add one?

We host DNS at Gandi. I think @evgeni and I are the only ones with an account there now.

I've now created a CNAME record.

> Is it expected that `http://web01.osuosl.theforeman.org/` serves the same page as `deb.theforeman.org` ?

Apache has virtual hosts and I think the best way to describe that is the (relevant) output from `httpd -S`:
```
# httpd -S
VirtualHost configuration:
*:443                  is a NameVirtualHost
         default server archivedeb.theforeman.org (/etc/httpd/conf.d/25-archivedeb-https.conf:6)
         port 443 namevhost archivedeb.theforeman.org (/etc/httpd/conf.d/25-archivedeb-https.conf:6)
         port 443 namevhost deb.theforeman.org (/etc/httpd/conf.d/25-deb-https.conf:6)
         port 443 namevhost debugs.theforeman.org (/etc/httpd/conf.d/25-debugs-https.conf:6)
         port 443 namevhost downloads.theforeman.org (/etc/httpd/conf.d/25-downloads-https.conf:6)
         port 443 namevhost stagingdeb.theforeman.org (/etc/httpd/conf.d/25-stagingdeb-https.conf:6)
         port 443 namevhost stagingyum.theforeman.org (/etc/httpd/conf.d/25-stagingyum-https.conf:6)
         port 443 namevhost theforeman.org (/etc/httpd/conf.d/25-web-https.conf:6)
                 alias www.theforeman.org
         port 443 namevhost yum.theforeman.org (/etc/httpd/conf.d/25-yum-https.conf:6)
*:80                   is a NameVirtualHost
         default server archivedeb.theforeman.org (/etc/httpd/conf.d/25-archivedeb.conf:6)
         port 80 namevhost archivedeb.theforeman.org (/etc/httpd/conf.d/25-archivedeb.conf:6)
         port 80 namevhost deb.theforeman.org (/etc/httpd/conf.d/25-deb.conf:6)
         port 80 namevhost debugs.theforeman.org (/etc/httpd/conf.d/25-debugs.conf:6)
         port 80 namevhost downloads.theforeman.org (/etc/httpd/conf.d/25-downloads.conf:6)
         port 80 namevhost stagingdeb.theforeman.org (/etc/httpd/conf.d/25-stagingdeb.conf:6)
         port 80 namevhost stagingyum.theforeman.org (/etc/httpd/conf.d/25-stagingyum.conf:6)
         port 80 namevhost theforeman.org (/etc/httpd/conf.d/25-web.conf:6)
                 alias www.theforeman.org
         port 80 namevhost yum.theforeman.org (/etc/httpd/conf.d/25-yum.conf:6)
ServerRoot: "/etc/httpd"
Main DocumentRoot: "/etc/httpd/htdocs"
Main ErrorLog: "/var/log/httpd/error_log"
Mutex ssl-stapling: using_defaults
Mutex ssl-cache: using_defaults
Mutex default: dir="/run/httpd/" mechanism=default 
Mutex mpm-accept: using_defaults
Mutex authdigest-opaque: using_defaults
Mutex rewrite-map: using_defaults
Mutex authdigest-client: using_defaults
PidFile: "/etc/httpd/run/httpd.pid"
Define: _RH_HAS_HTTPPROTOCOLOPTIONS
Define: DUMP_VHOSTS
Define: DUMP_RUN_CFG
User: name="apache" id=48
Group: name="apache" id=48
```

You can see that `web01.osuosl.theforeman.org` isn't explicitly mentioned so it falls back to the default, which is `archivedeb`, not `deb`

**Comment by ehelms** [comment]
@evgeni - is there some configuration needed? 


```
Fastly error: unknown domain: stagingyum.theforeman.org. Please check that this domain has been added to a service.

Details: cache-pdk17874-PDK
```

**Comment by ekohl** [comment]
Where do you get that error? Let's Encrypt? We do have a bit of a bootstrap problem with it: IIRC you first need the HTTP vhost to exist before you can request the HTTPS certificate. Perhaps that's the problem here?

**Comment by ehelms** [comment]
That error is at http://stagingyum.theforeman.org

**Comment by ekohl** [comment]
Ah, we need to set up the CDN as well. Previously @evgeni has used https://github.com/theforeman/foreman-infra/blob/d3863fb95c0ee6085f9b8f0ce698f8f6970eb95f/ansible/fastly.yml#L37-L42 to set that part up.

**Pull request merged**
