### PR TITLE
set 120 mins timeout for katello-pr-test

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by mmoll** [comment]
I hope this also works for the groovy jobs...

**Comment by komidore64** [comment]
I think for pipeline jobs it is cleaner to keep as much configuration in groovy as possible.

```groovy
pipeline {
    [...]
    options {
        timestamps()
        timeout(time: 2, unit: 'HOURS')
        ansiColor('xterm')
        buildDiscarder(logRotator(numToKeepStr: '15'))
    }
    [...]

}
```

**Comment by komidore64** [comment]
Or would it make even more sense to have a default timeout of 120 mins for all jobs? Those that need more can override.

**Comment by mmoll** [comment]
Seems this would only be possible with a workaround... https://issues.jenkins-ci.org/browse/JENKINS-26778

**Comment by mmoll** [comment]
edited the grovvy script now.

**Pull request merged**
