### PR TITLE
Hide verbose rvm output in jobs

### PR DESCRIPTION
**Pull request by ehelms**
Per a conversation on IRC with @timogoebel this would hide the overly verbose RVM output.

### CODE REVIEW

**Comment by timogoebel** [comment]
I'd suggest adding a little note, that RVM is being set up.

```
echo "Setting up RVM environment.";
set +x
whatever
set -x
```

**Comment by ehelms** [comment]
@timogoebel Updated

**Comment by ekohl** [comment]
I'll let Travis finish before I merge it.

**Comment by timogoebel** [comment]
@ekohl : Tests are 🍏 .

**Comment by ekohl** [comment]
Thanks!

**Pull request merged**
