### PR TITLE
Add JJB version of deploy_katello_site

### PR DESCRIPTION
**Pull request by ehelms**
First attempt at converting a job over. I picked something simple that has no other job dependencies to get my feet wet.

### CODE REVIEW

**Comment by GregSutcliffe** [comment]
Looks sensible, thanks! I'll try to review the XML diff soon, if someone doesn't beat me to it ;)

**Comment by ehelms** [comment]
I forgot that step myself, inspecting the XML, so feel free to hold off until I do so myself.

**Comment by ehelms** [comment]
My cursory glance, and even attempt to use an XML diff tool seemed sane although the little differences between the 2 make it much harder to parse than it should be.

**Comment by domcleal** [comment]
Thanks @ehelms.  It should deploy within 40 mins or so, I'll let you know if I see any error reports.

**Pull request merged**
