### PR TITLE
use relative path when archiving artifacts

### PR DESCRIPTION
**Pull request by evgeni**
otherwise archiveArtifacts rejects the path

### CODE REVIEW

**Review by ekohl — COMMENTED** [review]
The default is relative:

https://github.com/theforeman/foreman-infra/blob/5b3037739b6f46f3847711c17a6bf2cffaf1a69f/puppet/modules/jenkins_job_builder/files/centos.org/ansible/jenkins_job.yml#L11

Here it's set to an absolute path:

https://github.com/theforeman/foreman-infra/blob/5b3037739b6f46f3847711c17a6bf2cffaf1a69f/puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/foreman-discovery-image.groovy#L21-L25

However, nowhere else it's actually set. Isn't that the real problem?

**Comment by evgeni** [comment]
It's set here:
https://github.com/theforeman/foreman-infra/blob/35c62a87cd9f1a78ea8ac95a5452e8104a590528/puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/lib/foreman_infra.groovy#L108-L111

And if you look at the error was:
```
09:18:44  Archiving artifacts
09:18:44  ‘/home/jenkins/workspace/foreman-2.2-release-pipeline/artifacts/foreman-pipeline-foreman-2.2-ubuntu1804-upgrade//**’ doesn’t match anything, but ‘artifacts/foreman-pipeline-foreman-2.2-ubuntu1804-upgrade//**’ does. Perhaps that’s what you mean?
09:18:44  No artifacts found that match the file pattern "/home/jenkins/workspace/foreman-2.2-release-pipeline/artifacts/foreman-pipeline-foreman-2.2-ubuntu1804-upgrade//**". Configuration error?
```

**Comment by evgeni** [comment]
I could try not defining the path as absolute to begin with?

**Review by ekohl — APPROVED** [review]
Let's try this.

**Pull request merged**
