### PR TITLE
Ensure the correct vagrant version is installed

### PR DESCRIPTION
**Pull request by ekohl**

### CODE REVIEW

**Comment by mmoll** [comment]
`Provider dpkg must have features 'versionable' to set 'ensure' to '2.0.2'` :crying_cat_face:

**Comment by ekohl** [comment]
I only tested this with yum :( I wonder if latest would work with local files

**Comment by ekohl** [comment]
Updated to use latest instead. This appears to work.

**Comment by mmoll** [comment]
merged, bedankt @ekohl!

**Pull request merged**
