### PR TITLE
packaging_test_pull_request_katello_rpm - JJB until 3.7

### PR DESCRIPTION
**Pull request by komidore64**

### CODE REVIEW

**Comment by ekohl** [comment]
Doesn't this obsolete the last old style PR testing? Shouldn't that be removed too?

**Comment by ekohl** [comment]
@ehelms I meant `ensure => absent` and remove the template like the other PRs. We still want to purge it from all servers before we actually remove the code.

**Comment by komidore64** [comment]
@ekohl urite. i always forget to to do that! what would i do without you?

**Comment by komidore64** [comment]
@ekohl updated!

**Comment by ehelms** [comment]
@komidore64 Yank this file too https://github.com/komidore64/foreman-infra/blob/b8477510176ed7dc5e6cb7443ee2c5cdf0584958/puppet/modules/slave/templates/test_pull_requests_katello_packaging.json.erb ?

**Comment by komidore64** [comment]
@ehelms bam!

**Comment by komidore64** [comment]
niiiiiiice! can do

**Pull request merged**
