### PR TITLE
Hammer cli foreman master release

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by ehelms** [comment]
Requires https://github.com/theforeman/foreman-infra/pull/933

**Comment by komidore64** [comment]
do a rebasey-base now that #933 is in.

**Comment by ehelms** [comment]
@komidore64 https://github.com/theforeman/foreman-infra/pull/933 is still hangin out there

**Comment by komidore64** [comment]
Pfft. I can't read. I saw "merged" but that's referencing another PR. Apologies.

**Comment by ehelms** [comment]
This is updated with a new test job and rebased on origin/master

**Pull request merged**
