### PR TITLE
Add postgresql-12 module to flat repos

### PR DESCRIPTION
**Pull request by Odilhao**

### CODE REVIEW

**Comment by ehelms** [comment]
@Odilhao needs a rebase now

**Comment by Odilhao** [comment]
@ehelms rebase done :smile:

**Review by ekohl — APPROVED** [review]
I forgot how this is exactly deployed. @ehelms?

**Comment by ehelms** [comment]
```
cd koji/
ansible-playbook playbooks/external_repos.yml
```

**Pull request merged**
